Program 1

In [6]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.corpus import stopwords
import string
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
def preprocess_text(text):
 # Tokenization
    tokens = word_tokenize(text.lower())
 # Remove punctuation
    tokens = [token for token in tokens if token not in string.punctuation]
 # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    return tokens
def lemmatize(tokens):
    lemmatizer = WordNetLemmatizer()
    lemmas = [lemmatizer.lemmatize(token) for token in tokens]
    return lemmas
def stem(tokens):
    
    stemmer = PorterStemmer()
    stems = [stemmer.stem(token) for token in tokens]
    return stems
def main():
 # Sample text
    text = "Tokenization is the process of breaking down text into words and phrases. Stemming and Lemmatization are techniques used to reduce words to their base form."

     # Preprocess text
    tokens = preprocess_text(text)
    print("tokens:",tokens)
     # Lemmatization
    lemmas = lemmatize(tokens)
    print("Lemmatization:")
    print(lemmas)
     # Stemming
    stems = stem(tokens)
    print("\nStemming:")
    print(stems)
if __name__ == "__main__": 
    main()


tokens: ['tokenization', 'process', 'breaking', 'text', 'words', 'phrases', 'stemming', 'lemmatization', 'techniques', 'used', 'reduce', 'words', 'base', 'form']

Lemmatization:
['tokenization', 'process', 'breaking', 'text', 'word', 'phrase', 'stemming', 'lemmatization', 'technique', 'used', 'reduce', 'word', 'base', 'form']

Stemming:
['token', 'process', 'break', 'text', 'word', 'phrase', 'stem', 'lemmat', 'techniqu', 'use', 'reduc', 'word', 'base', 'form']


Program 2

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Load the financial dataset
data = pd.read_csv("financial_dataset.csv")
# Assuming the dataset has two columns: "text" containing the text data and "sentiment" containing 
#sentiment labels
X = data['text']
y = data['sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Vectorize the text data using N-gram model
vectorizer = CountVectorizer(ngram_range=(1, 2)) # You can adjust the n-gram range
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)
# Train the classifier
classifier = MultinomialNB()
classifier.fit(X_train_vectorized, y_train)
# Predict sentiment on the test set
y_pred = classifier.predict(X_test_vectorized)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Program 3

In [8]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

C:\Users\srika\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [9]:
# Sample text data
text_data = [
 "This is the first document.",
 "This document is the second document.",
 "And this is the third one.",
 "Is this the first document?",
]

In [11]:
# i) One Hot Encoding
def one_hot_encoding(text_data):
    unique_words = set(" ".join(text_data).split())
    encoded_data = []
    for text in text_data:
        encoded_text = [1 if word in text else 0 for word in unique_words]
        encoded_data.append(encoded_text)
    return np.array(encoded_data)
one_hot_encoded = one_hot_encoding(text_data)
print("One Hot Encoding:")
print(one_hot_encoded)


One Hot Encoding:
[[0 0 0 0 0 1 1 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 1 1]
 [0 1 0 1 0 0 1 0 0 1 1 0 1]
 [1 0 1 1 0 0 1 0 1 0 0 1 1]]


In [12]:
# ii) Bag of Words (BOW)
vectorizer = CountVectorizer()
bow_features = vectorizer.fit_transform(text_data)
print("\nBag of Words (BOW):")
print(bow_features.toarray())


Bag of Words (BOW):
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [13]:
# iii) n-grams
ngram_vectorizer = CountVectorizer(ngram_range=(1, 2))
ngram_features = ngram_vectorizer.fit_transform(text_data)
print("\nn-grams:")
print(ngram_features.toarray())



n-grams:
[[0 0 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0]
 [0 0 2 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 0 1 0]
 [0 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1]]


In [14]:
# iv) Tf-Idf
tfidf_vectorizer = TfidfVectorizer()
tfidf_features = tfidf_vectorizer.fit_transform(text_data)
print("\nTf-Idf:")
print(tfidf_features.toarray())



Tf-Idf:
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [15]:
# v) Custom features (e.g., length of documents)
custom_features = np.array([[len(doc)] for doc in text_data])
print("\nCustom Features:")
print(custom_features)


Custom Features:
[[27]
 [37]
 [26]
 [27]]


In [21]:
from gensim.models import Word2Vec
import numpy as np

# Assuming 'text_data' is a list of strings
word2vec_model = Word2Vec([doc.split() for doc in text_data], min_count=1)
word2vec_features = np.array([np.mean([word2vec_model.wv[word] for word in doc.split()], axis=0) for doc in text_data]) 
print("\nWord2Vec (Word Embedding) Features:")
print(word2vec_features)



Word2Vec (Word Embedding) Features:
[[-6.65289070e-03  3.31369741e-03  4.08868713e-04  2.44881405e-04
  -5.88463910e-04 -2.59218062e-03  3.18747014e-03  5.55393519e-03
  -2.48023192e-03 -3.41991754e-03  1.00939209e-03 -5.74333710e-04
  -4.32855962e-03 -2.97620900e-05 -1.54151581e-04 -1.86934939e-03
   1.87192135e-03  6.28794252e-04 -3.34958662e-03 -1.97452726e-03
   6.29672548e-04 -2.17557978e-03  8.12448654e-03  3.46868369e-03
  -1.32092997e-03 -1.70423693e-04  8.27728480e-04  1.99035089e-03
  -2.87406426e-03  2.06327345e-03  3.14927706e-03 -3.12824314e-03
  -3.18707607e-04 -6.51314203e-03  2.79311393e-03  2.53376341e-03
   5.44173876e-03  5.51073055e-04  8.93780962e-04  2.49114865e-03
   2.61284830e-03 -2.20044097e-03 -5.72596490e-03 -1.55718997e-04
   1.92174525e-03  6.04374327e-05  7.91336061e-04  2.67658220e-03
   1.48482504e-03 -1.77320562e-05  2.14161794e-03 -1.79007486e-03
   7.77226523e-04 -2.61274923e-04 -1.91269221e-03 -2.16178130e-04
   3.14616645e-03 -1.51300768e-03 -1.33

Program 4

In [23]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD
import numpy as np

# Sample text data
documents = [
    "baseball soccer basketball",
    "soccer basketball tennis",
    "tennis cricket",
    "cricket soccer"
]

# Create a CountVectorizer to convert text data into a matrix of token counts
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Apply Latent Semantic Analysis (LSA)
lsa = TruncatedSVD(n_components=2)
X_lsa = lsa.fit(X)

# Extract the components/topics
terms = vectorizer.get_feature_names_out()
topic_matrix = np.array([lsa.components_[i] / np.linalg.norm(lsa.components_[i]) for i in range(lsa.components_.shape[0])])

# Print the topics
print("Top terms for each topic:")
for i, topic in enumerate(topic_matrix):
    top_indices = topic.argsort()[-5:][::-1]  # Get the top 5 terms for each topic
    top_terms = [terms[index] for index in top_indices]
    print(f"Topic {i + 1}: {' '.join(top_terms)}")


Top terms for each topic:
Topic 1: soccer basketball tennis cricket baseball
Topic 2: cricket tennis soccer baseball basketball
